### ISSUE TITLE
Starten?

### ISSUE THREAD

**Issue by JBlond** [MeFisto94/ddf-random#1]
Wie wird das gestartet? git clone und ddf-random/src/app.html im Browser öffnen gibt nur `%sveltekit.head% %sveltekit.body%` aus.Ein Hinweis im README wäre super.

**Comment by MeFisto94** [comment]
Eine Lösung für Nicht-Entwickler muss aber dennoch gefunden werden. Mindestens ein github actions, bei dem am Ende ein release-zip rauskommt, am Besten. Wenn es jemand hosten würde, wäre es natürlich noch einfacher.

**Comment by MeFisto94** [comment]
PR #2 sollte das implementieren. Je nach dem Laden allerdings aus Sicherheitsgründen die Album-Cover nicht (Mixed-Content).
https://github.com/YourMJK/dreimetadaten/issues/30

**Comment by MeFisto94** [comment]
Yep, https://github.com/MeFisto94/ddf-random/releases/tag/0.0.1 klappt, aber das Album Cover fehlt vermutlich

**Comment by JBlond** [comment]
Wie wäre es mit https://mefisto94.github.com ? Wie beschrieben in https://pages.github.com/
